### ISSUE TITLE
can't get tls mode to work?

### ISSUE THREAD

**Issue by jhaar** [deepfence/PacketStreamer#6]
Hi there

I just saw this released and had to give it a go. I got it working in non-tls mode (ie sensor pushing it's network data to a remote receiver), but when I added the tls lines to the before-working receiver.yaml it broke

```
input:
  address: 0.0.0.0
  port: 999
tls:
   enable: true
   certFile: /path/file.pem
   keyFile: /path/file.key
output:
  file:
    path: /var/spool/packstreamer/dump.pcap
```

It errors out with

```
2022/04/03 08:46:42 Start receiving
2022/04/03 08:46:42 Now waiting in main
2022/04/03 08:46:42 open : no such file or directory

```

I ran it via strace and the "open : " is

`<... openat resumed>)            = -1 ENOENT (No such file or directory)`

ie no filename, no file descriptor either? Remove those lines and it works again - sans tls of course. BTW it doesn't exit - but it doesn't listen on the port either - so it's dead.

strace also shows no attempt to open the certFile/keyFile

Any ideas? This is compiled and run under Fedora-35 with golang-1.16.15-1.fc35.x86_64

Thanks

Jason
